ARG VERSION=11.5.2

FROM grafana/grafana-oss:${VERSION}

ENV GF_ANALYTICS_REPORTING_ENABLED=false \
    GF_ANALYTICS_CHECK_FOR_UPDATES=false \
    GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false \
    GF_UNIFIED_ALERTING_ENABLED=false \
    GF_LOG_LEVEL=warn \
    GOMEMLIMIT=320MiB \
    GOGC=75 \
    GODEBUG=madvdontneed=1

# copy the datasources and dashboards
COPY datasources /etc/grafana/provisioning/datasources
COPY dashboards /etc/grafana/provisioning/dashboards
